require:
  - rubocop-rails

Style/FrozenStringLiteralComment: {Enabled: false}
Style/Documentation: {Enabled: false}

AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - config/**/*
