require:
  - rubocop-rails

Style/FrozenStringLiteralComment: {Enabled: false}
Style/Documentation: {Enabled: false}

AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - config/**/*

Rails/Output:
  Exclude:
    - db/seeds.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
